GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kosmos;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kosmos;